# Generated by Django 4.1 on 2024-12-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_artigos_noticia_data_criacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artigos',
            new_name='Artigo',
        ),
    ]
