# Generated by Django 4.1 on 2024-12-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_noticia_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='crud/'),
        ),
    ]
