# Generated by Django 5.1.4 on 2024-12-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('artigos', models.ManyToManyField(blank=True, related_name='colecoes', to='crud.artigo')),
                ('tags', models.ManyToManyField(blank=True, related_name='colecoes', to='crud.tag')),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artigos', to='crud.tag'),
        ),
    ]
