# Generated by Django 5.1.4 on 2024-12-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_tag_colecao_artigo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='descricao',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
