# Generated by Django 5.1.4 on 2024-12-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_tag_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='descricao',
            field=models.CharField(max_length=120),
        ),
    ]
