# Generated by Django 5.1.6 on 2025-02-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
